name: bangladesh_economy
description: A WebView app for bangladesh economy.
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # ওয়েব ভিউ এর জন্য এই প্যাকেজটি লাগবে
  webview_flutter: ^4.7.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
